### ISSUE TITLE
Efficent Implementation

### ISSUE THREAD

**Issue by phongnhhn92** [princeton-vl/RAFT#26]
Hello,
I would like to ask if I can use your Efficent Implementation of correlation layer during training. I have limited GPU memory but long training time is possible.

**Comment by zachteed** [comment]
Hi, actually using the efficient implementation during training won't significantly reduce the memory usage, since most of the memory during training is used to store the GRU activations.

How much memory do you have? I would recommend training with mixed precision with a smaller batch size, you should be able to get similar results with this training schedule

`python -u train.py --name raft-chairs --stage chairs --validation chairs --gpus 0 --num_steps 200000 --batch_size 4 --lr 0.00016 --image_size 368 496 --wdecay 0.00001 --mixed_precision`
