### ISSUE TITLE
Nice work, I am curious about model architecture.

### ISSUE THREAD

**Issue by shoutOutYangJie** [princeton-vl/RAFT#34]
Why do you discard all batchnorm after resNet backbone.  What is the reasion. How to consider to make this decision.

**Comment by shuuchen** [comment]
I also have similar questions.
I noticed that you used instance norm, which is popular used in style transfer. Is it according to experiment result or some theories ? 
Also, you multiplied 8 in unfold in raft.py, why ?
```python
up_flow = F.unfold(8 * flow, [3,3], padding=1)
```
I really appreciate you talking about them.

**Comment by WANG-KX** [comment]
Hi, the optical flow magnitude should be scaled up according to the upsampling factor. Here, the flow is upsampled by three pyramids, so 2**3 = 8.

About BatchNorm, I am also interested in the author's explaination. In my experience, PWCNet and some other monodepth works also do not have BatchNorm layers. I guess since the output distribution is not "gaussian", BatchNorm is not needed?

**Comment by zachteed** [comment]
Normalization can sometimes be problematic for regression tasks like optical flow, which is why normalization is not included in the GRU updates. 

Instance normalization in the feature encoder makes the network more robust to domain changes (ie cross dataset generalization) because normalizing across the spatial dimensions reduces appearance changes. I didn't find the type of normalization used in the context encoder to be that important, I found it can be removed without hurting performance.
