### ISSUE TITLE
why concate [x, flow]

### ISSUE THREAD

**Issue by libonwpu** [princeton-vl/RAFT#41]
Dear Zachary,

Thanks for your nice work of RAFT. It is elegant, powerful and of great novelty. I have a puzzle that why you concate [x, flow] before you input the x to GRUs.  Does it influence the results serious? I have not see any ablation study of this.

cheers

**Comment by zachteed** [comment]
Hi, I have not ablated over this particular design choice. I expect this could be removed without hurting performance because it is redundant, since features are already being extracted from the flow field. 

However, it did find it to be very important that the GRU has access to the current estimate of the flow field in some form (either direct concatenation or concatenating with flow features).

**Comment by libonwpu** [comment]
Thanks

> Hi, I have not ablated over this particular design choice. I expect this could be removed without hurting performance because it is redundant, since features are already being extracted from the flow field.
> 
> However, it did find it to be very important that the GRU has access to the current estimate of the flow field in some form (either direct concatenation or concatenating with flow features).

Thanks
