### ISSUE TITLE
kitti_15 and kitti_12 datasets

### ISSUE THREAD

**Issue by RokiaAbdeen** [princeton-vl/RAFT#78]
I want to ask about the testing folders that we should provide to get the testing results from kitti benchmark
I have trained two optical flow models : first is trained by Kitti_12 and second is trained by kitti_15. now I need to submit my testing results to kitti benckmark. I saved png of the testing flow images but for kitti_15 they required these folders
 (Provide a zip file which contains the 'disp_0' directory (stereo), the 'flow' directory (flow), or the 'disp_0', 'disp_1' and 'flow' directories (scene flow) in its root folder. Use the file format and naming described in the readme.txt (000000_10.png,...,000199_10.png). 
and I just have the flow images, when I tried to upload the flow images only I got this error
ERROR: Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB) 
for kitti_12 I have uploaded flow images but also got the same error could anyone please explain what should be the folders to upload for both datasets? what is disp_0 for kitti_15 and how to get it?

**Comment by zachteed** [comment]
I didn't submit to the kitti12 leaderboard, but for kitti15 you need to place all the predictions in a directory labeled flow, then run 

`zip -r submission.zip flow`

disp_0, and disp_1 are for disparity / scene flow prediction, so you can ignore them.

**Comment by RokiaAbdeen** [comment]
thanks so much for your reply
I just want to submit my own results, I saved the predicted flow of my model using your function frame_utils.writeFlowKITTI(file_name, flow )
I saved 200 images in this format 
![000008_10](https://user-images.githubusercontent.com/26867350/109244206-3db94680-7819-11eb-9d9d-6906df4611b7.png)
 but I am still getting this error
ERROR: Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
what should be the problem please

**Comment by RokiaAbdeen** [comment]
I tested only the left images (folder image_2), image size is torch.Size([1, 2, 376, 1241])

**Comment by RokiaAbdeen** [comment]
the problem was from the zipping program, not all zipped file is accepted
thanks again for your reply

**Comment by ReekiLee** [comment]
@RokiaAbdeen 
Hello!
  So sorry to bother you. I test this model on kitti_15 recently but I met some problems.
  First, the image size of kitti_15 is (1226, 370, 3) but the output of this model is (1232, 376, 2). I know it is because of padding and 8x upsampling, but how could I get the same H and W of the input image?
  Another one is about the  Inference Updates. The paper says "Although we unroll 12 updates during training, we can
apply an arbitrary number of updates during inference". Why? Do the updates have the same parameters with the 12 updates?
  These questions have puzzled me for a few days, and I want to ask if you can help me.
  Thank you in advance! Wish you success in your research.
