### ISSUE TITLE
 How the correlation lookup differs from the correlation layer in Flownet?

### ISSUE THREAD

**Issue by jingjin25** [princeton-vl/RAFT#91]
Hi, I am a little confused about the differences between the correlation used in your code and the correlation layer used in Flownet. It seems that they should be the same when the patch size of the latter one equal to 1. I am not sure if my understanding is correct. 

I want to know if there is any difference except the computational efficiency?

Thanks!

**Comment by zachteed** [comment]
Hi, your understanding is correct. The main difference is that we compute the correlation volume for all-pairs of pixels while FlowNetC uses a limited correlation range. We also iteratively index from the correlation volume which allows our approach to improve accuracy over multiple iterations. The computation of all-pairs correlation can actually be implemented very quickly because it can be performed as a single matrix multiplication for which there are highly optimized GPU kernels.

**Comment by jingjin25** [comment]
@zachteed  Many thanks!
