### ISSUE TITLE
Regarding align_corners=True

### ISSUE THREAD

**Issue by wpeebles** [princeton-vl/RAFT#94]
Hi, Congrats on the fantastic work. I was wondering if there is a specific motivation behind using `align_corners=True` when performing sampling. I usually see `grid_sample` being called with `align_corners=False` (presumably to preserve scale invariance), but I was curious if there was any particular reason for not doing so in RAFT.

**Comment by hzwer** [comment]
I have tested in some optical flow estimation networks, align_corners=True seems to make the result very slightly better.

**Comment by zachteed** [comment]
Hi, I'm assuming this is related to the bilinear_sampling operation here: https://github.com/princeton-vl/RAFT/blob/224320502d66c356d88e6c712f38129e60661e80/core/utils/utils.py#L65 . Basically, I generated several test cases and `align_corners=True` gave the expected behavior. For example, calling bilinear_sampler on a  coordinate grid generated by https://github.com/princeton-vl/RAFT/blob/224320502d66c356d88e6c712f38129e60661e80/core/utils/utils.py#L74 should be the identity map
